version: '3.9'

services:
  postgres_dev:
    image: postgres:14-alpine
    container_name: postgres_dev
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db

  postgres_test:
    image: postgres:14-alpine
    container_name: postgres_test
    ports:
      - "5433:5432"  # Use a different port to avoid conflicts
    volumes:
      - ~/apps/postgres_test:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db
 