services:
  db:
    image: postgres:14-alpine
    container_name: code_tutorial_app_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=${PGPASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
